config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'mypage/top'
  get 'mypage/edit'
  delete 'mypage/delete'
  patch 'mypage/update'
  get 'mypage/postEdit'

  root 'all_posts#all_post'
  get 'new_post', to: 'new_posts#new_post'
  get 'post_detail', to: 'post_details#post_detail'
  post 'send_post', to: 'new_posts#send_post'
  

  get 'search_cate', to: 'all_posts#search_category'
  get 'search_word', to: 'all_posts#search_word'
  get 'search_pref', to: 'all_posts#search_prefecture'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :prefectures
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, foreign_key: [:id]


end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user, optional: true
    belongs_to :category, optional: true, foreign_key: :category_id
    belongs_to :prefecture, optional: true, foreign_key: :prefecture_id
    
    validate :add_error_sample
    validates :title, length: { maximum: 20 }
    validates :content, length: { maximum: 200 }
    validates :from_age, presence: { message: 'を選択してください' }
    validates :to_age, presence: { message: 'を選択してください' }

    def add_error_sample
    
        if title.empty? and content.empty? then
            errors[:title] << "を入力してください！"
            errors[:content] << "を入力してください！"
    
        elsif title.empty? then
            errors[:title] << "を入力してください！"
  
        elsif content.empty? then
            errors[:content] << "を入力してください！"
        end   
    end


    def self.search_w(search)
        if search
            Post.where(['content LIKE ? OR title LIKE ?', "%#{search}%","%#{search}%"]).order(id: :desc)
        else
            Post.all.order(id: :desc)
        end
    end


end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
    has_many :posts, foreign_key: [:id]
    has_many :users
    belongs_to :area
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
         
  validates :nickname, uniqueness: true, presence: true, length: { maximum: 20 }

  has_many :posts
         
end

app/controllers/all_posts_controller.rb
class AllPostsController < ApplicationController

    def all_post



        @posts = Post.joins(:prefecture, :category).select("posts.*, prefectures.prefecture, categories.category").order(id: :desc)
        @categories = Category.all
    end
    
    def search_prefecture
        
        @posts = Post.joins(:prefecture, :category).where(prefecture_id: params[:prefecture_id]).select("posts.*, prefectures.prefecture, categories.category")
        @categories = Category.all
        render 'all_post'
    end


    def search_category
        @posts = Post.joins(:prefecture, :category).where(category_id: params[:category_id]).select("posts.*, prefectures.prefecture, categories.category")
        @categories = Category.all
        render 'all_post'
    end

    def search_word
        @posts = Post.search_w(params[:sitem])
        @categories = Category.all
        render 'all_post'
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def chatroom
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  def top
    @users = User.where(id: current_user.id).select("users.*")
    @posts = Post.where(user_id: current_user.id).select("posts.*")
    @postNumber = Post.where(user_id: current_user.id).count

  end

  def edit
    require 'pry'
    @users = User.where(id: current_user.id).select("users.*")
    binding.pry
  end

  def delete
    #ログインユーザーのIDをdevice導入後に変更する
    @post = Post.find(params[:postId])
    @post.destroy

    @users = User.where(id: current_user.id).select("users.*")
    @posts = Post.where(user_id: current_user.id).select("posts.*")
    @postNumber = Post.where(user_id: current_user.id).count
    render :top

  end

  def postEdit
    @posts = Post.find(params[:postId])
    
    

end 

def update
  #ログインユーザーのIDをdevice導入後に変更する
    @posts = Post.find(params[:post][:id])
    if @posts.update(update_params)
 
      @users = User.where(id: params[:post][:user_id]).select("users.*")
      @posts = Post.where(user_id: params[:post][:user_id]).select("posts.*")
      @postNumber = Post.where(user_id: params[:post][:user_id]).count
      render :top
    else
        @posts.errors.full_messages
        @posts = Post.find(params[:post][:id])
        
        render :postEdit
    end
end

def update_params

  params.require(:post).permit(:prefecture_id, :category_id, :title, :content, :accept_number, :from_age, :to_age, :id, :user_id, :created_at)

end
end

app/controllers/new_posts_controller.rb
class NewPostsController < ApplicationController
    before_action :authenticate_user!
    def new_post

        @posts = Post.new


    end


    def send_post
        @posts = Post.new(post_params)
        if @posts.save
            redirect_to root_path 
        else
            @posts.errors.full_messages
            render :new_post
        end
        

        
    end
private


    def post_params
        params.require(:post).permit(:prefecture_id, :category_id, :title, :content, :accept_number, :from_age, :to_age).merge(user_id: current_user.id)

    end



end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def Index
    end
end

app/helpers/all_post_helper.rb
module AllPostHelper
end

app/helpers/all_posts_helper.rb
module AllPostsHelper
end

app/helpers/application_form_builder.rb
class ApplicationFormBuilder < Actionview::Helpers:::ApplicationFormBuilder
    attr_reader :vue_data

  def initialize(object_name, object, template, options)
    super(object_name, object, template, options)

    # Vue の初期化時に渡すデータを保持するハッシュ
    @vue_data = {}
  end
  
    def select_vue(methid, choices = [], potions = {}, html_options ={}, &block)
        html_options = inject_vmodel(method, html_options)
        select(method, choices, options, html_options, &block)
    end

    def inject_vmodel(model, html_options)

        @vue_data[method] = object[method]
        html_options.merge('v-model': method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def simple_time(time)
        time.strftime("%Y-%m-%d %H:%M ")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/new_post_helper.rb
module NewPostHelper
end

app/helpers/new_posts_helper.rb
module NewPostsHelper
end

app/helpers/post_details_helper.rb
module PostDetailsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/all_posts/all_post.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>新規投稿</title>
<link rel="stylesheet" type="text/scss" href="/app/assets/stylesheets/all_posts.scss">
</head>
<body>
<header>
		<div class="share-header">
			<div class="h-contents">
				<div class="h-component">
					<div class="h-component-h1">地元の掲示板 Suchmos</div>
				</div>
				<div class="h-flex-component">
					<div class="number-of-data">
						<a class="click-link-black" href="">00000000件 5/18日更新 地元の掲示板 Suchmos</a>
					</div>
					<div class="h-a-flex">
						<%= link_to("ホームへ", { controller: "all_posts", action: "all_post"}, {method: :get, class: "begnner"}) %> 
						<%if user_signed_in? %>
							<%= link_to "ログアウト", users_sign_out_path, method: :delete, class: "session_btn" %>
						<% else %>
							<%= link_to "ログイン", user_session_path, class: "session_btn" %>
						<% end %>
							<%= link_to("マイページ", { controller: "mypage", action: "top"}, class: "mypage-button") %> 
						<div class="h-regist-button">
							<%= link_to "新規登録", new_user_session_path, class: "r-button" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
<%= button_to "新しく投稿する",{controller: "new_posts", action: "new_post"}, {method: :get, class: "new_post_btn"} %>
<div id="submenu">
<div id="submenu_header">キーワードから探す</div>
<div id="sample">

<%= form_tag(search_word_path,:method => 'get') do %>
<input type="text" name="sitem" class="text" placeholder="キーワードを入れてください"><!--検索キーワード-->
<input value="検索" type="submit" class="btn"><!--検索ボタン-->
<% end %>
</div><br>

		<div id="submenu_header">カテゴリーから探す</div>
		<ul id="submenu_body">
		<% @categories.each do |category| %>
			<%= link_to category.category, search_cate_path(:category_id => category.id) %>
			<% end %>
		</ul>
		<div id="search_header">都道府県から探す</div>
		<div id="search_body">

<%= form_tag(search_pref_path, method: "get") do %>			
<div class="pulldown">
<%= select_tag :prefecture_id, options_from_collection_for_select(Prefecture.all, :id, :prefecture) %>
</div>
<input id="sbtn1" type="submit" value="検索" />
		</div>
	</div>
	<% end %>
<% @posts.each do |post| %>
<ul class = "onePost">
<li class="onePost_1">

<%= link_to post.title, controller: "post_details", action: "post_detail", id: post.id %>
<div id="category">
		<p class="cate" ><%= post.category.category %></p>
		</div>
<div class="a">
<div class="post_date">投稿日時：<%= simple_time(post.created_at) %></div>
		<div class="from_area">場所：[<%= post.prefecture.prefecture %>]</div>
</div>
		</li>
</ul>
<% end %>

</body>
</html>

app/views/new_posts/new_post.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>◎新規投稿◎</title>
 <script type="text/javascript" src="new_post.js"></script>
<link rel="stylesheet" type="text/css" href="new_post.css?201610261213">
</head>
<body>
<% if @posts.errors.any? %>
  <div id="error_explanation">
    <h2><%= @posts.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @posts.errors.full_messages.each do |msg| %>
      <li>・<%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form_body">
<%= form_for(@posts, url: send_post_path) do |f| %>

<div class ="pulldown" id ="area_id">場所：

<%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture %>
</div><br>
<div class ="pulldown">
カテゴリ：<%= f.collection_select :category_id, Category.all, :id, :category %>
</div>
<br>
<div class ="pulldown">
募集人数：<%= f.select :accept_number, options_for_select(1..200) %>
</div>
<br>
<div class ="pulldown">
募集最低年齢：<%= f.select :from_age, {"最低年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
    </div>
    <br>
    <div class ="pulldown">
募集最高年齢：<%= f.select :to_age, {"最高年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
     </div>
<br>






     <%= f.text_field :title, :placeholder => "タイトルを20文字以内で入力してください", :maxlength => "20" %>
  <%= f.text_area :content, :placeholder => "本文を300文字以内で入力してください", :maxlength => "200" %>
  <div class = "button_wrapper">
  <%= f.submit "投稿する", id: "post_button", name: "post_submit"%>
</div>
</div>
<% end %>
</body>
</html>

app/views/new_posts/postEdit.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>◎新規投稿◎</title>
 <script type="text/javascript" src="new_post.js"></script>
<link rel="stylesheet" type="text/scss" href="/app/assets/stylesheets/postEdit.scss">
</head>
<body>
<% if @posts.errors.any? %>
  <div id="error_explanation">
    <h2><%= @posts.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @posts.errors.full_messages.each do |msg| %>
      <li>・<%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form_body">
<%= form_for(@posts, url: new_posts_update_path) do |f| %>

<div class ="pulldown" id ="area_id">場所：

<%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture %>
</div><br>
<div class ="pulldown">
カテゴリ：<%= f.collection_select :category_id, Category.all, :id, :category %>
</div>
<br>
<div class ="pulldown">
募集人数：<%= f.select :accept_number, options_for_select(1..200) %>
</div>
<br>
<div class ="pulldown">
募集最低年齢：<%= f.select :from_age, {"最低年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
    </div>
    <br>
    <div class ="pulldown">
募集最高年齢：<%= f.select :to_age, {"最高年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
     </div>
<br>






     <%= f.text_field :title, :placeholder => "タイトルを20文字以内で入力してください", :maxlength => "20" %>
  <%= f.text_area :content, :placeholder => "本文を300文字以内で入力してください", :maxlength => "200" %>
  <div class = "button_wrapper">
  <%= f.submit "更新する", id: "post_button", name: "post_submit"%>
</div>
</div>
<% end %>
</body>
</html>