config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'mypage/top'
  get 'mypage/edit'
  delete 'mypage/delete'
  patch 'mypage/update'
  get 'mypage/postEdit'

  root 'all_posts#all_post'
  get 'new_post', to: 'new_posts#new_post'
  get 'post_detail', to: 'post_details#post_detail'
  post 'send_post', to: 'new_posts#send_post'
  

  get 'search_cate', to: 'all_posts#search_category'
  get 'search_word', to: 'all_posts#search_word'
  get 'search_pref', to: 'all_posts#search_prefecture'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :prefectures
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, foreign_key: [:id]


end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user, optional: true
    belongs_to :category, optional: true, foreign_key: :category_id
    belongs_to :prefecture, optional: true, foreign_key: :prefecture_id
    
    validate :add_error_sample
    validates :title, length: { maximum: 20 }
    validates :content, length: { maximum: 200 }
    validates :from_age, presence: { message: 'を選択してください' }
    validates :to_age, presence: { message: 'を選択してください' }

    def add_error_sample
    
        if title.empty? and content.empty? then
            errors[:title] << "を入力してください！"
            errors[:content] << "を入力してください！"
    
        elsif title.empty? then
            errors[:title] << "を入力してください！"
  
        elsif content.empty? then
            errors[:content] << "を入力してください！"
        end   
    end


    def self.search_w(search)
        if search
            Post.where(['content LIKE ? OR title LIKE ?', "%#{search}%","%#{search}%"]).order(id: :desc)
        else
            Post.all.order(id: :desc)
        end
    end


end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
    has_many :posts, foreign_key: [:id]
    has_many :users
    belongs_to :area
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
         
  validates :nickname, uniqueness: true, presence: true, length: { maximum: 20 }

  has_many :posts
         
end

app/controllers/all_posts_controller.rb
class AllPostsController < ApplicationController

    def all_post



        @posts = Post.joins(:prefecture, :category).select("posts.*, prefectures.prefecture, categories.category").order(id: :desc)
        @categories = Category.all
    end
    
    def search_prefecture
        
        @posts = Post.joins(:prefecture, :category).where(prefecture_id: params[:prefecture_id]).select("posts.*, prefectures.prefecture, categories.category")
        @categories = Category.all
        render 'all_post'
    end


    def search_category
        @posts = Post.joins(:prefecture, :category).where(category_id: params[:category_id]).select("posts.*, prefectures.prefecture, categories.category")
        @categories = Category.all
        render 'all_post'
    end

    def search_word
        @posts = Post.search_w(params[:sitem])
        @categories = Category.all
        render 'all_post'
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def chatroom
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  def top
    @users = User.where(id: current_user.id).select("users.*")
    @posts = Post.where(user_id: current_user.id).select("posts.*")
    @postNumber = Post.where(user_id: current_user.id).count

  end

  def edit
    require 'pry'
    @users = User.where(id: current_user.id).select("users.*")
    binding.pry
  end

  def delete
    #ログインユーザーのIDをdevice導入後に変更する
    @post = Post.find(params[:postId])
    @post.destroy

    @users = User.where(id: current_user.id).select("users.*")
    @posts = Post.where(user_id: current_user.id).select("posts.*")
    @postNumber = Post.where(user_id: current_user.id).count
    render :top

  end

  def postEdit
    @posts = Post.find(params[:postId])
    
    

end 

def update
  #ログインユーザーのIDをdevice導入後に変更する
    @posts = Post.find(params[:post][:id])
    if @posts.update(update_params)
 
      @users = User.where(id: params[:post][:user_id]).select("users.*")
      @posts = Post.where(user_id: params[:post][:user_id]).select("posts.*")
      @postNumber = Post.where(user_id: params[:post][:user_id]).count
      render :top
    else
        @posts.errors.full_messages
        @posts = Post.find(params[:post][:id])
        
        render :postEdit
    end
end

def update_params

  params.require(:post).permit(:prefecture_id, :category_id, :title, :content, :accept_number, :from_age, :to_age, :id, :user_id, :created_at)

end
end

app/controllers/new_posts_controller.rb
class NewPostsController < ApplicationController
    before_action :authenticate_user!
    def new_post

        @posts = Post.new


    end


    def send_post
        @posts = Post.new(post_params)
        if @posts.save
            redirect_to root_path 
        else
            @posts.errors.full_messages
            render :new_post
        end
        

        
    end
private


    def post_params
        params.require(:post).permit(:prefecture_id, :category_id, :title, :content, :accept_number, :from_age, :to_age).merge(user_id: current_user.id)

    end



end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def Index
    end
end

app/helpers/all_post_helper.rb
module AllPostHelper
end

app/helpers/all_posts_helper.rb
module AllPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def simple_time(time)
        time.strftime("%Y-%m-%d %H:%M ")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/new_post_helper.rb
module NewPostHelper
end

app/helpers/new_posts_helper.rb
module NewPostsHelper
end

app/helpers/post_details_helper.rb
module PostDetailsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/mypage/edit.html.erb
<header>
		<div class="share-header">
			<div class="h-contents">
				<div class="h-component">
					<div class="h-component-h1">地元の掲示板 Suchmos</div>
				</div>
				<div class="h-flex-component">
					<div class="number-of-data">
						<a class="click-link-black" href="">00000000件 5/18日更新 地元の掲示板 Suchmos</a>
					</div>
					<div class="h-a-flex">
						<a class="begnner" href="">初めての方へ</a> <a class="login-button"
							rel="nofollow" href="">ログイン</a>
						<div class="h-regist-button">
							<a class="r-buttom" rel="nofollow" href="">会員登録</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

<h3 class="mypage_edit_h3">編集ページ</h3>
<div class="mypege_edit">
	<dl>
		<dt>お名前</dt>
		<dd><input type="text" name="name" size="30" maxlength="20" ></dd>
	
		<dt>ユーザー名</dt>
		<dd><input type="text" name="user_name" size="6" maxlength="4" ></dd>

		<dt>メールアドレス</dt>
		<dd><input type="email" name="mail" size="6" maxlength="4" ></dd>

		<dt>都道府県</dt>
		<dd><input type="text" name="prefecture" size="6" maxlength="4" ></dd>

		<dt>最終更新日時：</dt>

		<dt>投稿数：</dt>
	</dl>
</div>



<footer>
		<ul>
			<li>
				<a target="_blank" href="">利用規約</a>
			</li>
			<li>

				|

				<a target="_blank" href="">プライバシーポリシー</a>
			</li>
			<li>

				|

				<a target="_blank" href="">健康課に資する運用方針</a>
			</li>
			<li>
				|
				<a target="_blank" href="">お問い合わせ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">運営会社</a>
			</li>
			<li>

				|

				<a target="_blank" href="">サイトマップ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">特定商取引法の表示</a>
			</li>
			<div class="copyright">
			COPYRIGHT (C) 2011 - 2019 Jimoty, Inc. Shut up and listen.
			</div>
		</ul>
	</footer>

app/views/mypage/postEdit.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>◎新規投稿◎</title>
<link rel="stylesheet" type="text/scss" href="/app/assets/stylesheets/postEdit.scss">
</head>
<body>
<% if @posts.errors.any? %>
  <div id="error_explanation">
    <h2><%= @posts.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @posts.errors.full_messages.each do |msg| %>
      <li>・<%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form_body">
<%= form_for(@posts, url: mypage_update_path) do |f| %>

<div class ="pulldown" id ="area_id">場所：

<%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture %>
</div><br>
<div class ="pulldown">
カテゴリ：<%= f.collection_select :category_id, Category.all, :id, :category %>
</div>
<br>
<div class ="pulldown">
募集人数：<%= f.select :accept_number, options_for_select(1..200) %>
</div>
<br>
<div class ="pulldown">
募集最低年齢：<%= f.select :from_age, {"最低年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
    </div>
    <br>
    <div class ="pulldown">
募集最高年齢：<%= f.select :to_age, {"最高年齢を選んでください" => "", "20歳" => "20", "25歳" => "25", "30歳" => "30", "35歳" => "35", "40歳" => "40", "45歳" => "45", "50歳" => "50", "55歳" => "55", "60歳" => "60"} %>
     </div>
<br>






     <%= f.text_field :title, :placeholder => "タイトルを20文字以内で入力してください", :maxlength => "20" %>
  <%= f.text_area :content, :placeholder => "本文を300文字以内で入力してください", :maxlength => "200" %>
  <%= f.hidden_field :created_at %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :id %>
  <div class = "button_wrapper">
  <%= f.submit "更新する", id: "post_button", name: "post_submit"%>
</div>
</div>
<% end %>
</body>
</html>

app/views/mypage/top.html.erb
<header>
		<div class="share-header">
			<div class="h-contents">
				<div class="h-component">
					<div class="h-component-h1">地元の掲示板 Suchmos</div>
				</div>
				<div class="h-flex-component">
					<div class="number-of-data">
						<a class="click-link-black" href="">00000000件 5/18日更新 地元の掲示板 Suchmos</a>
					</div>
					<div class="h-a-flex">
						<%= link_to("ホームへ", { controller: "all_posts", action: "all_post"}, {method: :get, class: "begnner"}) %> 
						<a class="login-button"
							rel="nofollow" href="">ログイン</a>
							<%= link_to("マイページ", { controller: "mypage", action: "top", id: 1 }, class: "mypage-button") %>
						<div class="h-regist-button">
							<a class="r-buttom" rel="nofollow" href="">会員登録</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<% @users.each do |user| %>
<div class="mypage-body">
<label></label>
<h3 class="user-info">ユーザーネーム：<%= user.nickname %></h3>
<h3 class="user-info">メールアドレス：<%= user.email %></h3>
<h3 class="user-info">誕生日：<%= user.birthday %></h3>
<h3 class="user-info">都道府県：<%= user.prefecture_id %></h3>
<h3 class="user-info">更新日時：<%= simple_time(user.updated_at) %></h3>
<h3 class="user-info">投稿数： <%= @postNumber %></h3>
<%= button_to "プロフィールを編集する",{controller: "mypage", action: "edit"}, {method: :get, class: "profile-edit-btn"} %>
</div>
<% end %>
<h1>★今までの投稿</h1>
<div class="all-post">
<% @posts.each do |post| %>
<div class="one-post">
<h3 class="post-info"><span cless="title-label">■タイトル : </span><%= post.title %></h3>
<h3 class="post-info"><span class="update-label">■更新日時 : </span><%= simple_time(post.updated_at) %></h3>
<%= link_to("編集", { controller: "mypage", action: "postEdit", postId: post.id}, {method: :get, class: "delete-button"}) %>
<%= link_to("削除", { controller: "mypage", action: "delete", postId: post.id}, {method: :delete, class: "edit-button"}) %>
</div>
<% end %>
</div>
<footer>
		<ul>
			<li>
				<a target="_blank" href="">利用規約</a>
			</li>
			<li>

				|

				<a target="_blank" href="">プライバシーポリシー</a>
			</li>
			<li>

				|

				<a target="_blank" href="">健康課に資する運用方針</a>
			</li>
			<li>
				|
				<a target="_blank" href="">お問い合わせ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">運営会社</a>
			</li>
			<li>

				|

				<a target="_blank" href="">サイトマップ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">特定商取引法の表示</a>
			</li>
			<div class="copyright">
			COPYRIGHT (C) 2011 - 2019 Jimoty, Inc. Shut up and listen.
			</div>
		</ul>
	</footer>

app/views/top/index.html.erb
<header>
		<div class="share-header">
			<div class="h-contents">
				<div class="h-component">
					<div class="h-component-h1">地元の掲示板 Suchmos</div>
				</div>
				<div class="h-flex-component">
					<div class="number-of-data">
						<a class="click-link-black" href="">00000000件 5/18日更新 地元の掲示板 Suchmos</a>
					</div>
					<div class="h-a-flex">
						<a class="begnner" href="">初めての方へ</a> <a class="login-button"
							rel="nofollow" href="">ログイン</a>
						<div class="h-regist-button">
							<a class="r-buttom" rel="nofollow" href="">会員登録</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

    <footer>
		<ul>
			<li>
				<a target="_blank" href="">利用規約</a>
			</li>
			<li>

				|

				<a target="_blank" href="">プライバシーポリシー</a>
			</li>
			<li>

				|

				<a target="_blank" href="">健康課に資する運用方針</a>
			</li>
			<li>
				|
				<a target="_blank" href="">お問い合わせ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">運営会社</a>
			</li>
			<li>

				|

				<a target="_blank" href="">サイトマップ</a>
			</li>
			<li>

				|

				<a target="_blank" href="">特定商取引法の表示</a>
			</li>
			<div class="copyright">
			COPYRIGHT (C) 2011 - 2019 Jimoty, Inc. Shut up and listen.
			</div>
		</ul>
	</footer>